import { SiNotion } from "react-icons/si";
import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaReddit,
  FaWhatsapp,
  FaFacebook,
  FaTwitter,
  FaSpotify,
  FaInstagram,
  FaYoutube,
  FaGamepad,
  FaTwitch,
  FaStackOverflow,
  FaAmazon,
  FaArtstation,
  FaBehance,
  FaEvernote,
  FaFigma,
  FaMedium,
  FaNpm,
  FaSnapchatGhost,
  FaFlickr,
  FaFlipboard,
  FaSteam,
  FaTumblr,
} from "react-icons/fa";

export const iconsList = [
  ["discord.com", FaDiscord],
  ["github.com", FaGithub],
  ["reddit.com", FaReddit],
  ["linkedin.com", FaLinkedin],
  ["whatsapp.com", FaWhatsapp],
  ["notion.so", SiNotion],
  ["facebook.com", FaFacebook],
  ["twitter.com", FaTwitter],
  ["spotify.com", FaSpotify],
  ["instagram.com", FaInstagram],
  ["youtube.com", FaYoutube],
  ["trueachievements.com", FaGamepad],
  ["twitch.tv", FaTwitch],
  ["stackoverflow.com", FaStackOverflow],
  ["amazon.com", FaAmazon],
  ["artstation.com", FaArtstation],
  ["behance.net", FaBehance],
  ["evernote.com", FaEvernote],
  ["figma.com", FaFigma],
  ["medium.com", FaMedium],
  ["npmjs.com", FaNpm],
  ["snapchat.com", FaSnapchatGhost],
  ["flickr.com", FaFlickr],
  ["flipboard.com", FaFlipboard],
  ["steampowered.com", FaSteam],
  ["tumblr.com", FaTumblr],
];
